nats:
  image: nats
  ports:
    - 4222:4222

publisher:
  image: mrako/nats-example-publisher
  command: ./wait-for nats:4222 -- npm start
  ports:
    - 9000:9000
  links:
    - nats

subscriber:
  image: mrako/nats-example-subscriber
  command: ./wait-for nats:4222 -- npm start
  links:
    - nats
