version: '3'

services:
  nats:
    image: nats
    ports:
      - 4222:4222

  frontend:
    build: frontend
    environment:
      - ENDPOINT=http://0.0.0.0:9000
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 8000:8000

  publisher:
    build: publisher
    command: ./wait-for nats:4222 -- node src/index.js
    ports:
      - 9000:9000
    volumes:
      - ./publisher/src:/usr/src/app/src

  subscriber:
    build: subscriber
    command: ./wait-for nats:4222 -- node src/index.js
    volumes:
      - ./subscriber/src:/usr/src/app/src
