nats:
  image: nats
  ports:
    - 4222:4222

frontend:
  image: mrako/nats-example_frontend
  environment:
    - ENDPOINT=${ENDPOINT}
  labels:
    io.rancher.scheduler.affinity:host_label: type=lb
  ports:
    - 9001:8000

publisher:
  image: mrako/nats-example_publisher
  command: ./wait-for nats:4222 -- node src/index.js
  labels:
    io.rancher.scheduler.affinity:host_label: type=lb
  ports:
    - 9000:9000
  links:
    - nats

subscriber:
  image: mrako/nats-example_subscriber
  command: ./wait-for nats:4222 -- node src/index.js
  links:
    - nats
