version: '3'

services:
  nats:
    image: nats
    ports:
      - 4222:4222

  publisher:
    build: publisher
    command: ./wait-for nats:4222 -- npm run dev
    ports:
      - 9000:9000
    volumes:
      - ./publisher/src:/usr/src/app/src

  subscriber:
    build: subscriber
    command: ./wait-for nats:4222 -- npm run dev
    volumes:
      - ./subscriber/src:/usr/src/app/src
